import React, { createContext, useContext, useState } from 'react';

const translations = {
  en: {
    appTitle: 'KrishiSeva AI',
    tagline: 'Smart Soil Diagnostic & Multilingual Government Scheme Guidance',
    navHome: 'Dashboard',
    navSoil: 'Soil Quality Diagnostic',
    navSchemes: 'Government Schemes',
    navChat: 'AI Scheme Assistant',
    navAdmin: 'Admin Console',
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    welcomeFarmer: 'Welcome, Farmer',
    soilHeader: 'Portable Soil Quality Analysis',
    soilDesc: 'Enter NPK, pH, and Moisture levels or pair your portable Bluetooth sensor to receive AI crop recommendations.',
    analyzeBtn: 'Analyze Soil & Get Crop Advice',
    schemesHeader: 'Government Welfare Schemes',
    schemesDesc: 'Explore subsidies, insurance, and financial grants curated for your farm.',
    aiChatHeader: 'Multilingual Scheme AI Advisor',
    aiChatDesc: 'Ask questions in Hindi, Marathi, Telugu, Tamil, or English via voice or text.',
    howToApply: 'How to Apply',
    readAloud: 'Read aloud',
    stopReading: 'Stop reading',
    stepsTitle: 'STEPS',
    docsTitle: 'DOCUMENTS NEEDED',
    viewDocsBtn: 'How to Apply & Documents',

    // Soil Analysis Form & Labels
    soilNutrientHeader: 'Soil Nutrient Parameters & Image Upload',
    soilPhotoUpload: 'Soil Texture / Plot Photo Upload',
    takeLivePhoto: 'Take Live Photo',
    dragOrCamera: 'Click / Drag Image or Use Camera Above',
    nitrogenLabel: 'Nitrogen (N) [kg/ha]',
    phosphorusLabel: 'Phosphorus (P) [kg/ha]',
    potassiumLabel: 'Potassium (K) [kg/ha]',
    phLabel: 'Soil pH Balance',
    moistureLabel: 'Moisture (%)',
    organicCarbonLabel: 'Organic Carbon (%)',
    soilTypeLabel: 'Soil Type',
    plotAliasLabel: 'Plot Name / Alias',
    pairBluetoothBtn: 'Pair Portable Bluetooth Sensor',
    pairingSensor: 'Pairing IoT NPK Sensor...',
    sensorSynced: 'IoT Probe Synced (100%)',
    aiDiagnosticSummary: 'AI Soil Diagnostic & Agronomic Machine Learning Model',
    recommendedCrops: 'AI Recommended High-Yield Crops',
    fertilizerPlan: 'Customized Soil Nutrient & Fertilizer Dosage Plan',

    // Home / Dashboard
    nextGenTitle: 'Next-Gen Autonomous Agriculture',
    heroDesc: 'Experience AI-driven soil diagnostics, real-time weather forecasting, and instant multilingual government welfare scheme access designed for high-yield farming.',
    launchSoilBtn: 'Launch Soil Diagnostic →',
    exploreSchemesBtn: 'Explore Welfare Schemes',
    todayWeatherHeader: "TODAY'S WEATHER",
    view3DayForecast: 'View 3-Day Forecast',
    threeDayForecastTitle: '3-Day Agricultural Weather Forecast',
    iotTelemetry: 'IoT Sensor Telemetry',
    avgSoilHealth: 'Avg Soil Health',
    yieldGain: 'Yield Gain Potential',
    humidity: 'Humidity',
    wind: 'Wind',
    solar: 'Solar',
    verifiedFarmer: 'Verified Farmer',
    newSoilTest: 'New Soil Test',
    askAiAssistant: 'Ask AI Assistant',
    activeCropHealthHeader: 'Active Crop Health & AI Agronomic Feed',
    farmingRemindersHeader: 'Farming Reminders',
    pendingTasks: 'Pending',
    addCustomTaskPlaceholder: 'Add custom task (e.g. Water Plot B)...',
    todayText: 'Today',
    tomorrowText: 'Tomorrow',
    inDaysText: 'In 3 Days',
    savedSchemesHeader: 'Saved Schemes & Subsidies',
    browseAllBtn: 'Browse All →',
    noSavedSchemesText: 'No saved schemes. Bookmark schemes on the Welfare Scheme page for quick access.',
    cropCalendarHeader: 'Kharif Crop Calendar (August)',
    topDressingTitle: 'Top Dressing Fertilization',
    topDressingDesc: 'Urea + MOP application for Cotton plot',
    pestScoutingTitle: 'Pest Scouting Day',
    pestScoutingDesc: 'Inspect pink bollworm pheromone traps',

    // Schemes Page
    schemesTagline: 'Verified Government Subsidies, Grants & Credit Assistance',
    allSchemesTab: 'All Government Schemes',
    bookmarkedTab: 'Bookmarked Schemes',
    searchPlaceholder: 'AI Smart Search (e.g., PM-KISAN, ₹6,000, Drip Subsidy, Solar Pump)...',
    stateLabel: 'State',
    districtLabel: 'District',
    cropLabel: 'Crop',
    landSizeLabel: 'Land Size (Acres)',
    farmerCategoryLabel: 'Farmer Category',
    schemeTypeLabel: 'Scheme Type',
    allStatesOption: 'All India / States',
    allDistrictsOption: 'All Districts',
    allCropsOption: 'All Crops',
    allCategoriesOption: 'All Categories',
    allTypesOption: 'All Types',
    financialAssistance: 'Financial Assistance',
    insuranceCredit: 'Insurance & Credit',
    solarIrrigation: 'Solar & Irrigation',
    machineryInfra: 'Machinery & Infrastructure',
    organicSoilHealth: 'Organic & Soil Health',
    alliedLivestock: 'Livestock & Fisheries',
    directBenefits: 'DIRECT SCHEME BENEFITS:',
    maxLand: 'Max Land:',
    deadline: 'Deadline:',

    // ChatBot Side Panels
    chatPlaceholder: 'Ask anything about crops, soil nutrients, or government subsidies...',
    voiceListening: 'Listening to your voice...',
    uploadCropPhoto: 'Upload crop / soil image',
    takeLivePhotoChat: 'Take live crop photo',
    inputMethods: 'INPUT METHODS',
    kisanHelplines: 'KISAN HELPLINES',
    pestDiagnosisTitle: 'Pest Diagnosis',
    irrigationPlanningTitle: 'Irrigation Planning',
    fertilizerDosageTitle: 'Fertilizer Dosage',
    farmingPracticesTitle: 'Farming Practices',
    voiceInputInfo: 'Voice Input',
    voiceOutputInfo: 'Voice Output',
    imageDiagnosisInfo: 'Image Diagnosis',
    multilingualInfo: 'Multilingual',

    // Contact Us Section
    navContact: 'Contact Us',
    contactTitle: 'Get in Touch with KrishiMitra AI',
    contactSubtitle: 'Have questions about soil reports, government schemes, or technical assistance? Our team is here to support you 24/7.',
    emailUsTitle: 'Email Support',
    emailAddress: 'krushimitra.work@gmail.com',
    callUsTitle: 'Call & WhatsApp Support',
    phoneNumber: '7875648995',
    phoneFormatted: '+91 7875648995',
    workingHours: 'Mon - Sat: 8:00 AM - 8:00 PM IST',
    officeAddressTitle: 'AgTech Innovation Center',
    officeAddress: 'KrishiMitra AgTech Hub, Krishi Bhavan Road, Nagpur, Maharashtra - 440001',
    kisanHelplineTitle: '24/7 Kisan Helpline',
    kisanHelplineNumber: '1800-180-1551 (Toll-Free)',
    sendUsMessage: 'Send Us a Direct Message',
    yourName: 'Your Full Name',
    yourPhone: 'Phone Number / Email',
    selectCategory: 'Select Query Category',
    soilReportQuery: 'Soil Quality Report & Testing',
    schemeAssistanceQuery: 'Government Welfare Schemes',
    techSupportQuery: 'Mobile / Web App Technical Help',
    generalFeedbackQuery: 'General Inquiry & Feedback',
    yourMessage: 'Your Message or Query',
    sendMessageBtn: 'Send Message',
    messageSentSuccess: 'Thank you! Your message has been sent successfully. We will get back to you shortly.',
    copyEmailBtn: 'Copy Email',
    copiedSuccess: 'Copied to clipboard!',
    chatOnWhatsApp: 'Chat on WhatsApp',

    // Navbar
    lightMode: 'Light Mode',
    darkMode: 'Dark Mode',
  },
  hi: {
    appTitle: 'कृषिसेवा AI',
    tagline: 'स्मार्ट मिट्टी गुणवत्ता जांच एवं बहुभाषी सरकारी योजना मार्गदर्शन',
    navHome: 'डैशबोर्ड',
    navSoil: 'मिट्टी स्वास्थ्य जांच',
    navSchemes: 'सरकारी योजनाएं',
    navChat: 'AI योजना सहायक',
    navAdmin: 'एडमिन पैनल',
    login: 'लॉग इन',
    register: 'पंजीकरण',
    logout: 'लॉग आउट',
    welcomeFarmer: 'नमस्ते, किसान मित्र',
    soilHeader: 'पोर्टेबल मिट्टी गुणवत्ता विश्लेषण',
    soilDesc: 'NPK, pH और नमी मान दर्ज करें या फसल सिफारिशों के लिए ब्लूटूथ सेंसर कनेक्ट करें।',
    analyzeBtn: 'मिट्टी की जांच करें और सलाह पाएं',
    schemesHeader: 'सरकारी कल्याणकारी योजनाएं',
    schemesDesc: 'अपनी खेती के लिए सब्सिडी, फसल बीमा और वित्तीय अनुदान की जानकारी प्राप्त करें।',
    aiChatHeader: 'बहुभाषी AI योजना सहायक',
    aiChatDesc: 'आवाज या पाठ द्वारा हिंदी, मराठी, या अंग्रेजी में सवाल पूछें।',
    howToApply: 'आवेदन कैसे करें',
    readAloud: 'बोलकर सुनें',
    stopReading: 'रोकें',
    stepsTitle: 'आवेदन के चरण (प्रक्रिया)',
    docsTitle: 'आवश्यक दस्तावेज',
    viewDocsBtn: 'आवेदन प्रक्रिया व दस्तावेज',

    // Soil Analysis Form & Labels
    soilNutrientHeader: 'मिट्टी के पोषक तत्व मान व फोटो अपलोड',
    soilPhotoUpload: 'मिट्टी / खेत की फोटो अपलोड',
    takeLivePhoto: 'लाइव फोटो खींचें',
    dragOrCamera: 'फोटो अपलोड करें या ऊपर दिए गए कैमरे का उपयोग करें',
    nitrogenLabel: 'नाइट्रोजन (N) [किग्रा/हेक्टेयर]',
    phosphorusLabel: 'फास्फोरस (P) [किग्रा/हेक्टेयर]',
    potassiumLabel: 'पोटेशियम (K) [किग्रा/हेक्टेयर]',
    phLabel: 'मिट्टी का pH संतुलन',
    moistureLabel: 'नमी (मॉइस्चर %)',
    organicCarbonLabel: 'जैविक कार्बन (%)',
    soilTypeLabel: 'मिट्टी का प्रकार',
    plotAliasLabel: 'खेत / प्लॉट का नाम',
    pairBluetoothBtn: 'पोर्टेबल ब्लूटूथ सेंसर कनेक्ट करें',
    pairingSensor: 'IoT NPK सेंसर कनेक्ट हो रहा है...',
    sensorSynced: 'IoT सेंसर कनेक्ट हो गया (100%)',
    aiDiagnosticSummary: 'AI मिट्टी जांच एवं कृषि मशीन लर्निंग मॉडल',
    recommendedCrops: 'AI द्वारा अनुशंसित उच्च उपज वाली फसलें',
    fertilizerPlan: 'अनुकूलित मृदा पोषक तत्व एवं उर्वरक खुराक योजना',

    // Home / Dashboard
    nextGenTitle: 'अगली पीढ़ी की स्वायत्त कृषि',
    heroDesc: 'उच्च उपज खेती के लिए AI मिट्टी जांच, वास्तविक समय मौसम पूर्वानुमान और सरकारी कल्याणकारी योजनाओं की जानकारी प्राप्त करें।',
    launchSoilBtn: 'मिट्टी की जांच शुरू करें →',
    exploreSchemesBtn: 'सरकारी योजनाएं देखें',
    todayWeatherHeader: 'आज का मौसम',
    view3DayForecast: '3-दिन का मौसम पूर्वानुमान देखें',
    threeDayForecastTitle: '3-दिवसीय कृषि मौसम पूर्वानुमान',
    iotTelemetry: 'IoT सेंसर डेटा',
    avgSoilHealth: 'औसत मिट्टी स्वास्थ्य',
    yieldGain: 'उपज वृद्धि क्षमता',
    humidity: 'नमी',
    wind: 'हवा की गति',
    solar: 'सौर ऊर्जा',
    verifiedFarmer: 'सत्यापित किसान',
    newSoilTest: 'नई मिट्टी जांच',
    askAiAssistant: 'AI सहायक से पूछें',
    activeCropHealthHeader: 'सक्रिय फसल स्वास्थ्य एवं AI एग्रोनॉमिक फीड',
    farmingRemindersHeader: 'कृषि रिमाइंडर',
    pendingTasks: 'लंबित',
    addCustomTaskPlaceholder: 'नया कार्य जोड़ें (उदा. खेत B में सिंचाई)...',
    todayText: 'आज',
    tomorrowText: 'कल',
    inDaysText: '3 दिनों में',
    savedSchemesHeader: 'सहेजी गई सरकारी योजनाएं व सब्सिडी',
    browseAllBtn: 'सभी देखें →',
    noSavedSchemesText: 'कोई सहेजी गई योजना नहीं है। त्वरित पहुँच के लिए योजना पृष्ठ पर बुकमार्क करें।',
    cropCalendarHeader: 'खरीफ फसल कैलेंडर (अगस्त)',
    topDressingTitle: 'टॉप ड्रेसिंग उर्वरक प्रयोग',
    topDressingDesc: 'कपास प्लॉट के लिए यूरिया + MOP का छिड़काव',
    pestScoutingTitle: 'कीट निगरानी दिवस',
    pestScoutingDesc: 'गुलाबी सुंडी फेरोमोन जाल की जांच करें',

    // Schemes Page
    schemesTagline: 'सत्यापित सरकारी सब्सिडी, वित्तीय अनुदान व ऋण सहायता',
    allSchemesTab: 'सभी सरकारी योजनाएं',
    bookmarkedTab: 'बुकमार्क की गई योजनाएं',
    searchPlaceholder: 'स्मार्ट खोज (जैसे: पीएम-किसान, ₹6,000, ड्रिप सब्सिडी, सोलर पंप)...',
    stateLabel: 'राज्य',
    districtLabel: 'जिला',
    cropLabel: 'फसल',
    landSizeLabel: 'जमीन (एकड़)',
    farmerCategoryLabel: 'किसान श्रेणी',
    schemeTypeLabel: 'योजना का प्रकार',
    allStatesOption: 'सभी राज्य / भारत',
    allDistrictsOption: 'सभी जिले',
    allCropsOption: 'सभी फसलें',
    allCategoriesOption: 'सभी श्रेणियां',
    allTypesOption: 'सभी प्रकार',
    financialAssistance: 'वित्तीय सहायता',
    insuranceCredit: 'बीमा व ऋण',
    solarIrrigation: 'सौर व सिंचाई',
    machineryInfra: 'मशीनरी व अवसंरचना',
    organicSoilHealth: 'जैविक व मिट्टी स्वास्थ्य',
    alliedLivestock: 'पशुपालन व मत्स्य',
    directBenefits: 'प्रत्यक्ष योजना लाभ:',
    maxLand: 'अधिकतम भूमि:',
    deadline: 'अंतिम तिथि:',

    // ChatBot Side Panels
    chatPlaceholder: 'फसलों, मिट्टी के पोषण, या सरकारी सब्सिडी के बारे में पूछें...',
    voiceListening: 'आपकी आवाज सुन रहे हैं...',
    uploadCropPhoto: 'फसल या मिट्टी की फोटो अपलोड करें',
    takeLivePhotoChat: 'लाइव फोटो खींचें',
    inputMethods: 'इनपुट माध्यम',
    kisanHelplines: 'किसान हेल्पलाइन',
    pestDiagnosisTitle: 'कीट एवं रोग निदान',
    irrigationPlanningTitle: 'सिंचाई योजना',
    fertilizerDosageTitle: 'उर्वरक खुराक',
    farmingPracticesTitle: 'कृषि पद्धतियां',
    voiceInputInfo: 'वॉयस इनपुट',
    voiceOutputInfo: 'वॉयस आउटपुट',
    imageDiagnosisInfo: 'चित्र द्वारा निदान',
    multilingualInfo: 'बहुभाषी',

    // Contact Us Section
    navContact: 'संपर्क करें',
    contactTitle: 'कृषिसेवा AI से संपर्क करें',
    contactSubtitle: 'मिट्टी रिपोर्ट, सरकारी योजनाओं या तकनीकी सहायता के लिए हमारी टीम 24/7 आपकी सेवा में उपलब्ध है।',
    emailUsTitle: 'ईमेल सहायता',
    emailAddress: 'krushimitra.work@gmail.com',
    callUsTitle: 'फोन व व्हाट्सएप सहायता',
    phoneNumber: '7875648995',
    phoneFormatted: '+91 7875648995',
    workingHours: 'सोम - शनि: सुबह 8:00 से रात 8:00 बजे तक',
    officeAddressTitle: 'कृषि तकनीक नवाचार केंद्र',
    officeAddress: 'कृषिसेवा AI एगटेक हब, कृषि भवन रोड, नागपुर, महाराष्ट्र - 440001',
    kisanHelplineTitle: '24/7 किसान हेल्पलाइन',
    kisanHelplineNumber: '1800-180-1551 (टोल-फ्री)',
    sendUsMessage: 'हमें सीधा संदेश भेजें',
    yourName: 'आपका पूरा नाम',
    yourPhone: 'फोन नंबर / ईमेल',
    selectCategory: 'प्रश्न की श्रेणी चुनें',
    soilReportQuery: 'मिट्टी गुणवत्ता रिपोर्ट व जांच',
    schemeAssistanceQuery: 'सरकारी कल्याणकारी योजनाएं',
    techSupportQuery: 'मोबाइल / वेब ऐप तकनीकी सहायता',
    generalFeedbackQuery: 'सामान्य पूछताछ व सुझाव',
    yourMessage: 'आपका संदेश या प्रश्न',
    sendMessageBtn: 'संदेश भेजें',
    messageSentSuccess: 'धन्यवाद! आपका संदेश सफलतापूर्वक भेज दिया गया है। हम जल्द ही आपसे संपर्क करेंगे।',
    copyEmailBtn: 'ईमेल कॉपी करें',
    copiedSuccess: 'क्लिपबोर्ड में कॉपी हो गया!',
    chatOnWhatsApp: 'व्हाट्सएप पर चैट करें',

    // Navbar
    lightMode: 'लाइट मोड',
    darkMode: 'डार्क मोड',
  },
  mr: {
    appTitle: 'कृषिसेवा AI',
    tagline: 'स्मार्ट माती गुणवत्ता तपासणी व बहुभाषिक शासकीय योजना मार्गदर्शन',
    navHome: 'डॅशबोर्ड',
    navSoil: 'माती आरोग्य तपासणी',
    navSchemes: 'शासकीय योजना',
    navChat: 'AI योजना सल्लागार',
    navAdmin: 'अ‍ॅडमिन पॅनेल',
    login: 'लॉग इन',
    register: 'नोंदणी करा',
    logout: 'लॉग आउट',
    welcomeFarmer: 'नमस्कार, शेतकरी मित्र',
    soilHeader: 'पोर्टेबल माती गुणवत्ता विश्लेषण',
    soilDesc: 'NPK, pH आणि आर्द्रता प्रविष्ट करा किंवा ब्लूटूथ सेन्सर कनेक्ट करा.',
    analyzeBtn: 'माती तपासा आणि पिकांचा सल्ला घ्या',
    schemesHeader: 'शासकीय योजना व सबसिडी',
    schemesDesc: 'कृषी सबसिडी, पिक विमा आणि अर्थसहाय्य योजनांची माहिती मिळवा.',
    aiChatHeader: 'बहुभाषिक AI योजना सहाय्यक',
    aiChatDesc: 'मराठी, हिंदी किंवा इंग्रजीत बोलून अथवा टाईप करून प्रश्न विचारा.',
    howToApply: 'अर्ज कसा करावा',
    readAloud: 'मोठ्याने ऐका',
    stopReading: 'थांबवा',
    stepsTitle: 'अर्जाचे टप्पे (प्रक्रिया)',
    docsTitle: 'आवश्यक कागदपत्रे',
    viewDocsBtn: 'अर्ज प्रक्रिया व कागदपत्रे',

    // Soil Analysis Form & Labels
    soilNutrientHeader: 'मातीचे पोषक घटक आणि फोटो अपलोड',
    soilPhotoUpload: 'मातीचा नमुना / शेताचा फोटो अपलोड',
    takeLivePhoto: 'थेट फोटो काढा',
    dragOrCamera: 'फोटो अपलोड करा किंवा वरील कॅमेरा वापरा',
    nitrogenLabel: 'नायट्रोजन (N) [किलो/हेक्टर]',
    phosphorusLabel: 'फॉस्फरस (P) [किलो/हेक्टर]',
    potassiumLabel: 'पोटॅशियम (K) [किलो/हेक्टर]',
    phLabel: 'मातीचे pH प्रमाण',
    moistureLabel: 'आर्द्रता (%)',
    organicCarbonLabel: 'सेंद्रिय कर्ब (%)',
    soilTypeLabel: 'मातीचा प्रकार',
    plotAliasLabel: 'शेताचे नाव',
    pairBluetoothBtn: 'ब्लूटूथ सेन्सर कनेक्ट करा',
    pairingSensor: 'IoT NPK सेन्सर जोडला जात आहे...',
    sensorSynced: 'IoT सेन्सर कनेक्ट झाला (१००%)',
    aiDiagnosticSummary: 'AI माती तपासणी व कृषी मशिन लर्निंग मॉडेल',
    recommendedCrops: 'AI द्वारे शिफारस केलेली पिके',
    fertilizerPlan: 'खत आणि पोषक घटक नियोजन',

    // Home / Dashboard
    nextGenTitle: 'पुढील पिढीची प्रगत शेती',
    heroDesc: 'उत्कृष्ट पिकांसाठी AI माती तपासणी, हवामान अंदाज आणि शासकीय योजनांचा लाभ घ्या.',
    launchSoilBtn: 'माती तपासणी सुरू करा →',
    exploreSchemesBtn: 'शासकीय योजना पहा',
    todayWeatherHeader: 'आजचे हवामान',
    view3DayForecast: '३ दिवसांचा हवामान अंदाज पहा',
    threeDayForecastTitle: '३ दिवसांचा कृषी हवामान अंदाज',
    iotTelemetry: 'IoT सेन्सर माहिती',
    avgSoilHealth: 'सरासरी माती आरोग्य',
    yieldGain: 'उत्पादन वाढ क्षमता',
    humidity: 'आर्द्रता',
    wind: 'वाऱ्याचा वेग',
    solar: 'सौर ऊर्जा',
    verifiedFarmer: 'प्रमाणित शेतकरी',
    newSoilTest: 'नवीन माती तपासणी',
    askAiAssistant: 'AI सहाय्यकाला विचारा',
    activeCropHealthHeader: 'सक्रिय पीक आरोग्य आणि AI माहिती',
    farmingRemindersHeader: 'शेती आठवणी',
    pendingTasks: 'प्रलंबित',
    addCustomTaskPlaceholder: 'नवीन काम जोडा (उदा. शेतात पाणी द्या)...',
    todayText: 'आज',
    tomorrowText: 'उद्या',
    inDaysText: '३ दिवसात',
    savedSchemesHeader: 'सेव्ह केलेल्या शासकीय योजना व सबसिडी',
    browseAllBtn: 'सर्व पहा →',
    noSavedSchemesText: 'कोणतीही सेव्ह केलेली योजना नाही. त्वरित प्रवेशासाठी योजना पृष्ठावर सेव्ह करा.',
    cropCalendarHeader: 'खरीप पीक कॅलेंडर (ऑगस्ट)',
    topDressingTitle: 'टॉप ड्रेसिंग खत वापर',
    topDressingDesc: 'कापूस पिकासाठी युरिया + MOP वापर',
    pestScoutingTitle: 'कीड पाहणी दिवस',
    pestScoutingDesc: 'गुलाबी बोंडअळी कामगंध सापळे तपासा',

    // Schemes Page
    schemesTagline: 'प्रमाणित शासकीय सबसिडी, अनुदान व कर्ज सहाय्य',
    allSchemesTab: 'सर्व शासकीय योजना',
    bookmarkedTab: 'सेव्ह केलेल्या योजना',
    searchPlaceholder: 'शोधा (उदा. पीएम-किसान, ₹६,०००, ठिबक सिंचन, सौर पंप)...',
    stateLabel: 'राज्य',
    districtLabel: 'जिल्हा',
    cropLabel: 'पीक',
    landSizeLabel: 'जमीन (एकड)',
    farmerCategoryLabel: 'शेतकरी गट',
    schemeTypeLabel: 'योजनेचा प्रकार',
    allStatesOption: 'सर्व राज्ये / भारत',
    allDistrictsOption: 'सर्व जिल्हे',
    allCropsOption: 'सर्व पिके',
    allCategoriesOption: 'सर्व गट',
    allTypesOption: 'सर्व प्रकार',
    financialAssistance: 'वित्तीय अर्थसहाय्य',
    insuranceCredit: 'विमा आणि कर्ज',
    solarIrrigation: 'सौर आणि सिंचन',
    machineryInfra: 'यंत्रसामग्री व पायाभूत सुविधा',
    organicSoilHealth: 'सेंद्रिय व माती आरोग्य',
    alliedLivestock: 'पशुसंवर्धन व मत्स्यव्यवसाय',
    directBenefits: 'योजनेचे थेट फायदे:',
    maxLand: 'कमाल जमीन:',
    deadline: 'अंतिम मुदत:',

    // ChatBot Side Panels
    chatPlaceholder: 'पिके, खते, किंवा शासकीय सबसिडीबद्दल प्रश्न विचारा...',
    voiceListening: 'तुमचा आवाज ऐकत आहे...',
    uploadCropPhoto: 'पीक किंवा मातीचा फोटो अपलोड करा',
    takeLivePhotoChat: 'थेट फोटो काढा',
    inputMethods: 'इनपुट पर्याय',
    kisanHelplines: 'शेतकरी हेल्पलाइन',
    pestDiagnosisTitle: 'कीड व रोग निदान',
    irrigationPlanningTitle: 'सिंचन नियोजन',
    fertilizerDosageTitle: 'खत प्रमाण',
    farmingPracticesTitle: 'शेती पद्धती',
    voiceInputInfo: 'व्हॉइस इनपुट',
    voiceOutputInfo: 'व्हॉइस आउटपुट',
    imageDiagnosisInfo: 'फोटोद्वारे निदान',
    multilingualInfo: 'बहुभाषिक',

    // Contact Us Section
    navContact: 'संपर्क साधा',
    contactTitle: 'कृषिसेवा AI शी संपर्क साधा',
    contactSubtitle: 'माती अहवाल, शासकीय योजना किंवा तांत्रिक मदतीसाठी आमची टीम २४/७ आपल्या सेवेत उपलब्ध आहे.',
    emailUsTitle: 'ईमेल सहाय्य',
    emailAddress: 'krushimitra.work@gmail.com',
    callUsTitle: 'फोन व व्हॉट्सॲप सहाय्य',
    phoneNumber: '7875648995',
    phoneFormatted: '+91 7875648995',
    workingHours: 'सोम - शनि: सकाळी ८:०० ते रात्री ८:०० पर्यंत',
    officeAddressTitle: 'कृषी तंत्रज्ञान नवोपक्रम केंद्र',
    officeAddress: 'कृषिसेवा AI अ‍ॅगटेक हब, कृषी भवन रोड, नागपूर, महाराष्ट्र - ४४०००१',
    kisanHelplineTitle: '२४/७ शेतकरी हेल्पलाइन',
    kisanHelplineNumber: '1800-180-1551 (टोल-फ्री)',
    sendUsMessage: 'आम्हाला थेट संदेश पाठवा',
    yourName: 'तुमचे पूर्ण नाव',
    yourPhone: 'फोन नंबर / ईमेल',
    selectCategory: 'प्रश्नाचा प्रकार निवडा',
    soilReportQuery: 'माती गुणवत्ता अहवाल व तपासणी',
    schemeAssistanceQuery: 'शासकीय योजना मदत',
    techSupportQuery: 'अ‍ॅप तांत्रिक सहाय्य',
    generalFeedbackQuery: 'सामान्य विचारणा व अभिप्राय',
    yourMessage: 'तुमचा संदेश किंवा प्रश्न',
    sendMessageBtn: 'संदेश पाठवा',
    messageSentSuccess: 'धन्यवाद! तुमचा संदेश यशस्वीरित्या पाठवला गेला आहे. आम्ही लवकरच तुमच्याशी संपर्क साधू.',
    copyEmailBtn: 'ईमेल कॉपी करा',
    copiedSuccess: 'क्लिपबोर्डवर कॉपी झाले!',
    chatOnWhatsApp: 'व्हॉट्सॲपवर चॅट करा',

    // Navbar
    lightMode: 'लाइट मोड',
    darkMode: 'डार्क मोड',
  },
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState('en');

  const t = (key) => {
    return translations[lang]?.[key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
